# Generated by Django 3.1.2 on 2020-10-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_auto_20201020_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconfiguration',
            name='token_ok',
            field=models.BooleanField(default=False),
        ),
    ]
