# Generated by Django 3.1.2 on 2020-10-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0005_instagramconfiguration_token_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconfiguration',
            name='posts_refresh_date',
            field=models.DateTimeField(null=True, verbose_name='Last posts refresh'),
        ),
    ]
