# Generated by Django 3.1.2 on 2020-10-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0008_auto_20201020_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='socials.Tag'),
        ),
    ]
