# Generated by Django 3.1.2 on 2020-10-21 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("socials", "0011_auto_20201020_1123"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instagramconfiguration",
            name="app_id",
        ),
        migrations.RemoveField(
            model_name="instagramconfiguration",
            name="app_secret",
        ),
    ]
